apiVersion: otus.homework/v1
kind: MySQL
metadata:
  name: mysql-instance
  namespace: default
spec:
  image: mysql:5.7
  database: otus-database
  password: passwordotus # Так делать не нужно, следует использовать secret
  storage_size: 1Gi

